#############################################
#	Dual License: BSD-3-Clause AND MPL-2.0	#
#	Copyright (c) 2024, Adam Nogowski		#
#############################################

site_name: pytest-item-dict
site_description: Get a hierarchical dict of session.items
site_author: Adam Nogowski
site_url: https://anogowski.github.io/pytest-item-dict/

theme: readthedocs

repo_url: https://github.com/anogowski/pytest-item-dict

nav:
  - Home: index.md
  - Examples:
      - Overview: examples.md
      - JSON: examples/json.md
      - XML: examples/xml.md
  - API Reference:
      - Plugin: src/plugin.md
      - CollectionDict: src/collect_dict.md
      - TestDict: src/test_dict.md
      - Enums: src/item_dict_enums.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]
          options:
            docstring_style: numpy
            show_source: true
            show_signature_annotations: true
            separate_signature: true
